INSERT INTO trainings (id, description, level, training_Type) VALUES
                                                                  ('bcf0b3b3-4c8f-4b73-8d3e-09215f3f4991',
                                                                   'Challenge yourself with extreme weightlifting routines that test your strength and endurance. Our weightlifting sessions focus on proper technique and progressive overload, ensuring you achieve optimal results safely. Whether you’re a seasoned lifter or just starting out, our trainers tailor programs to your individual goals and abilities. Experience the thrill of pushing your limits with heavy squats, deadlifts, and bench presses. Join our community of weightlifting enthusiasts and transform your physique with each session.',
                                                                   'EXTREME', 'WEIGHTLIFTING'),

                                                                  ('b80a05d1-47c0-4de8-9319-7959e3c5933f',
                                                                   'Improve your endurance with our specialized cardio sessions designed to elevate your heart rate and burn calories effectively. Our cardio workouts cater to all fitness levels, offering a variety of high-intensity interval training (HIIT) and steady-state exercises. Whether your goal is weight loss, enhanced cardiovascular health, or athletic performance, our experienced trainers guide you through dynamic routines. From running and cycling to circuit training and aerobic exercises, discover the power of cardio in transforming your fitness journey.',
                                                                   'INTERMEDIATE', 'CARDIO'),

                                                                  ('bfd8339a-84d3-4f0c-a2ea-32d5b31428e4',
                                                                   'Engage in fun and challenging gymnastics sessions that improve your strength, flexibility, and coordination. Our gymnastics classes cater to beginners through advanced athletes, focusing on fundamental skills like handstands, flips, and balance beam techniques. Learn from certified coaches who create a supportive environment for mastering gymnastic maneuvers. Whether you’re aiming to compete or simply enjoy recreational gymnastics, our programs offer personalized attention and progress tracking. Join our community and experience the thrill of tumbling, vaulting, and mastering aerial maneuvers.',
                                                                   'HARD', 'GYMNASTICS'),

                                                                  ('a77f9d0d-f91d-4f5c-8df6-81d4f5a63935',
                                                                   'Take your CrossFit training to the next level with our high-intensity WODs (Workout of the Day) designed for advanced athletes. Our WOD sessions incorporate functional movements like squats, burpees, and kettlebell swings to improve strength and conditioning. Experience the camaraderie and motivation of training alongside dedicated athletes who push their limits every day. Our experienced coaches provide scalable workouts that challenge seasoned CrossFitters while accommodating individual fitness levels. Join our vibrant community and conquer each WOD with determination and perseverance.',
                                                                   'HARD', 'WOD'),

                                                                  ('a5ebd2a5-42c2-4b4c-8a28-c3bb0a05e276',
                                                                   'Embark on a unique fitness journey with HYROX training, a high-intensity fitness race that combines running and functional exercises. Designed for endurance athletes and fitness enthusiasts, HYROX challenges participants to complete a series of workouts in a competitive setting. Whether you’re aiming to improve your running speed or enhance overall fitness, our HYROX sessions offer a thrilling way to test your physical and mental resilience. Train alongside like-minded individuals and discover the thrill of pushing your limits in a supportive environment.',
                                                                   'EXTREME', 'HYROX'),

                                                                  ('adfe3a41-35d1-487a-9b44-8f19885b2d79',
                                                                   'Stay fit and active with our tailored MUMFIT programs designed specifically for busy moms. Our MUMFIT sessions focus on postnatal fitness, core strength, and overall wellness, helping mothers regain strength and energy. Led by experienced trainers, these sessions incorporate safe and effective exercises that address common postpartum challenges. Whether you’re looking to lose baby weight, improve stamina, or simply enjoy a supportive fitness community, MUMFIT offers personalized training plans to meet your unique needs. Join other moms in a welcoming environment and prioritize your health journey.',
                                                                   'BEGINNER', 'MUMFIT'),

                                                                  ('ab2d5470-8653-4656-9e35-f104c8c8cbe3',
                                                                   'Access all gym facilities with our Open Gym sessions designed for fitness enthusiasts of all levels. Our Open Gym membership allows you to utilize state-of-the-art equipment and facilities at your convenience. Whether you prefer strength training, cardio workouts, or functional exercises, our spacious gym provides ample space and resources for your fitness routine. Train independently or seek guidance from our expert trainers who are available to offer tips and support. Enjoy the flexibility of customizing your workout schedule and achieving your fitness goals in a motivating environment.',
                                                                   'INTERMEDIATE', 'OPENGYM');
