spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mode: DEVELOPMENT
  devtools:
    restart:
      enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${my_pass}
    username: ${my_username}
    url: jdbc:mysql://localhost:3306/crossfit_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
remember_me_key: ${remembermekey}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080

forex:
  api:
    key: ${FOREX_API_KEY}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"

countries:
  api:
    url: "https://restcountries.com/v3.1/all?fields=name,cca2"


