spring:
  messages:
    basename: messages
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mode: DEVELOPMENT
  devtools:
    restart:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${my_pass:}
    username: ${my_username:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/crossfit_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
remember_me_key: ${remembermekey}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE

        SQL: TRACE
      nodeValue: WARN
    blog: WARN
server:
  port: 8080

forex:
  api:
    key: ${FOREX_API_KEY}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"
    init-exchange-rates: true

countries:
  api:
    url: "https://restcountries.com/v3.1/all?fields=name,cca2"


mail:
  crossfit: "crossfit-stuttgart@gmail.com"
  host: ${MAILHOG_HOST:localhost}
  port: ${MAILHOG_PORT:1025}
  username: ${MAIL_USER}
  password: ${MAIL_PASSWORD}

workouts :
  api:
    allTrainingsUrl: http://${TRAININGS_HOST:localhost}:8081/crossfit-api/get-all-trainings
    baseUrl: http://${TRAININGS_HOST:localhost}:8081/crossfit-api

crossfit :
  api :
    mostRecentEvents : http://${EVENT_HOST:localhost}:8082/crossfit-community/events/most-recent
    publishUrl : http://${EVENT_HOST:localhost}:8082/crossfit-community/events/publish
    byIdUrl : http://${EVENT_HOST:localhost}:8082/crossfit-community/events/find/{id}
    allEvents: http://${EVENT_HOST:localhost}:8082/crossfit-community/events/all
    init-crossfit-events: true


cloudinary :
  cloud_name : ${CLOUDINARY_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret : ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_KEY}
  expiration: ${JWT_EXPIRATION}